apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-microservice
    spec:
      containers:
      - name: flask-microservice-container
        image:  ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/hello-world-flask:v1.0.0
        ports:
        - containerPort: 4567